### ISSUE TITLE
The link to the tutorial is broken

### ISSUE THREAD

**Issue by loudmu** [angeloashmore/prismic-next-app-router-demo#1]

**Comment by angeloashmore** [comment]
Hi @loudmu, thanks for checking out the repo!

The tutorial isn't out yet and is still being written.

I'll add a note to the README that the tutorial and this repository is unfinished. Be sure to check the [Prismic Blog](https://prismic.io/blog/) periodically and read the tutorial when it's out! 🙂

**Comment by angeloashmore** [comment]
The tutorial is published!

https://prismic.io/blog/how-to-use-prismic-with-nextjs-app-router
